Dmitry Puzyrev | K33402
Backend-ITMO-2021/Lecture-8 pull request #1
Opened 2021-05-15 13:47 UTC by dipuzyrev

https://user-images.githubusercontent.com/12683472/118363498-42320780-b59d-11eb-987b-3b14b9a1a51b.mov

2021-05-15 14:03 UTC, IlyaHalsky requested changes
Фильтер действует на всех пользователей
Если изменить фильтр и ввести новое сообщение фильтр сбрасывается у всех

2021-05-15 14:03 UTC, IlyaHalsky commented on src/main/scala/ru/ifmo/backend_2021/AppStatic.scala
> +      db.appendMessage(username, message, Option.unless(replyTo == "")(replyTo.toInt))
Option.unless(replyTo == "")(replyTo.toInt) -> replyTo.toIntOption

2021-05-15 14:03 UTC, IlyaHalsky commented on src/main/scala/ru/ifmo/backend_2021/ApplicationUtils.scala
> +    def buildMessageThread(message: Message, depth: Int, lb: ListBuffer[Frag], groupedMessages: Map[Option[Int], List[Message]]): Unit = {
Что за не искоренимая любовь к мутабельным объектам. Можно же просто вернуть результат

2021-05-15 17:45 UTC, dipuzyrev commented
Fixed

2021-05-16 15:34 UTC, IlyaHalsky commented
35

2021-05-16 15:34 UTC, closed without merging